# Generated by Django 4.0.3 on 2022-04-05 10:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academdegree',
            options={'verbose_name': 'Ученая степень', 'verbose_name_plural': 'Ученые степени'},
        ),
        migrations.AlterModelOptions(
            name='groupclass',
            options={'verbose_name': 'Группа студентов', 'verbose_name_plural': 'Группа студентов'},
        ),
        migrations.AlterModelOptions(
            name='studyworkload',
            options={'verbose_name': 'Учебная нагрузка', 'verbose_name_plural': 'Учебная нагрузка'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': 'Предметная область', 'verbose_name_plural': 'Предметная область'},
        ),
        migrations.AlterModelOptions(
            name='teacherjob',
            options={'verbose_name': 'Должность', 'verbose_name_plural': 'Должности'},
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='fio',
        ),
        migrations.AddField(
            model_name='studyworkload',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.groupclass'),
        ),
        migrations.AddField(
            model_name='studyworkload',
            name='sub_type',
            field=models.CharField(choices=[('Теория', 'Теоритическая часть'), ('Практика', 'Практическая часть')], max_length=100, null=True, verbose_name='Вид проводимого занятия'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='first_name',
            field=models.CharField(max_length=100, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='last_name',
            field=models.CharField(max_length=100, null=True, verbose_name='Фамилия'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='location',
            field=models.CharField(max_length=300, null=True, verbose_name='Место жительства'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='middle_name',
            field=models.CharField(max_length=100, null=True, verbose_name='Отчество'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Номер телефона'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='academdegree',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название ученой степени'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='academic_degree',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.academdegree'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.teacherjob'),
        ),
    ]
