# Generated by Django 4.0.3 on 2022-04-07 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_academdegree_options_alter_groupclass_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='academdegree',
            name='num_of_work_hours',
            field=models.IntegerField(null=True, verbose_name='Количество часов работы (расчет за один семестр)'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='hours_num',
            field=models.IntegerField(verbose_name='Количество часов (семестр)'),
        ),
    ]
