# Generated by Django 4.0.3 on 2022-04-07 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_academdegree_num_of_work_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='num_of_weeks',
            field=models.IntegerField(null=True, verbose_name='Количество учебных недель'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='hours_num',
            field=models.IntegerField(verbose_name='Количество академических часов (неделя)'),
        ),
    ]
