# Generated by Django 4.0.3 on 2022-04-08 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_subject_num_of_weeks_alter_subject_hours_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academdegree',
            name='num_of_work_hours',
        ),
        migrations.AddField(
            model_name='teacherjob',
            name='num_of_work_hours',
            field=models.IntegerField(null=True, verbose_name='Количество часов работы (расчет за один семестр)'),
        ),
    ]
